# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10VAGO48s9b65SMvny4fEqgoWfvNDSKY_
"""

import pandas as pd
df = pd.read_csv("alzheimers_disease_data.csv")
df.head()

df.info()

df.describe()

df.columns

print(df.shape)

df.duplicated().sum()

df.isnull().sum()

df.isna().sum()

import matplotlib.pyplot as plt

# Displaying Histograms
df.hist(figsize=(20,15))
plt.show()

"""📊 Analyse des Types de Données et Conversion"""

# Vérifier les types de données
print("Types de données:")
print(df.dtypes)

# Identifier les variables catégorielles (binaires 0/1)
binary_cols = []
continuous_cols = []

for col in df.columns:
    if col not in ['PatientID', 'DoctorInCharge', 'Diagnosis']:
        unique_vals = df[col].unique()
        if set(unique_vals).issubset({0, 1}):
            binary_cols.append(col)
        else:
            continuous_cols.append(col)

print(f"\nVariables binaires (0/1): {len(binary_cols)}")
print(binary_cols)
print(f"\nVariables continues: {len(continuous_cols)}")
print(continuous_cols)

"""🔍 Détection des Valeurs Aberrantes (Outliers)

"""

# Fonction pour détecter les outliers avec IQR
def detect_outliers_iqr(data, column):
    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    outliers = data[(data[column] < lower_bound) | (data[column] > upper_bound)]
    return len(outliers), lower_bound, upper_bound

# Analyser les outliers pour les variables continues
print("Analyse des outliers (méthode IQR):")
print("-" * 60)

outliers_summary = []
for col in continuous_cols:
    n_outliers, lower, upper = detect_outliers_iqr(df, col)
    percent = (n_outliers / len(df)) * 100
    outliers_summary.append({
        'Variable': col,
        'Outliers': n_outliers,
        'Pourcentage': f"{percent:.2f}%",
        'Borne_inf': round(lower, 2),
        'Borne_sup': round(upper, 2)
    })
    if n_outliers > 0:
        print(f"{col:25} | {n_outliers:3} outliers ({percent:5.2f}%) | Plage: [{lower:8.2f}, {upper:8.2f}]")

outliers_df = pd.DataFrame(outliers_summary)

"""📊 Visualisation des Distributions"""

import math
import matplotlib.pyplot as plt

n_cols = 5
n_features = len(continuous_cols)
n_rows = math.ceil(n_features / n_cols)

fig, axes = plt.subplots(n_rows, n_cols, figsize=(4*n_cols, 4*n_rows))
axes = axes.ravel()

for idx, col in enumerate(continuous_cols):
    axes[idx].boxplot(df[col], vert=True)
    axes[idx].set_title(col, fontsize=10)
    axes[idx].grid(True, alpha=0.3)

# Remove empty subplots
for i in range(idx + 1, len(axes)):
    fig.delaxes(axes[i])

plt.suptitle('Boxplots - Détection des Outliers', fontsize=16)
plt.tight_layout()
plt.show()

# Drop the 'Ethnicity' column
df_clean = df.drop(columns=['Ethnicity'])
print(f'Nouvelles dimensions : {df_clean.shape}')

# Drop the 'PatientID and DoctorInCharge ' column
df_clean = df.drop(['PatientID', 'DoctorInCharge'], axis=1)
print(f'Nouvelles dimensions : {df_clean.shape}')

# Remove 'Ethnicity' from continuous_cols if it exists
continuous_cols = [col for col in continuous_cols if col in df_clean.columns]

"""# 🎯 Feature engineering & Separation des features et de les cibles"""

# Créer une cible basée sur les scores MMSE
def classify_cognitive_decline(mmse):
    if mmse >= 24:
        return 0  # Normal
    elif mmse >= 18:
        return 1  # Déclin Léger
    elif mmse >= 10:
        return 2  # Déclin Modéré
    else:
        return 3  # Déclin Sévère

df_clean['CognitiveDecline'] = df_clean['MMSE'].apply(classify_cognitive_decline)

# Créer un score de risque de chute composite
# Basé sur: Age, PhysicalActivity (faible), Balance issues, etc.

df_clean['FallRisk'] = (
    (df_clean['Age'] > 75).astype(int) * 2 +
    (df_clean['PhysicalActivity'] < 2).astype(int) * 2 +
    (df_clean['ADL'] < 5).astype(int) * 3 +  # Activities of Daily Living faibles
    df_clean['Confusion'] * 2 +
    df_clean['Disorientation'] * 2
)

# Convertir en classes
df_clean['FallRiskLevel'] = pd.cut(df_clean['FallRisk'],
                              bins=[-1, 2, 5, 10],
                              labels=['Faible', 'Moyen', 'Élevé'])

# Score composite de risque d'événements
df_clean['EventRiskScore'] = (
    df_clean['HeadInjury'] * 4 +                    # Antécédent de trauma cranien (fort facteur)
    df_clean['CardiovascularDisease'] * 3 +         # Maladie cardiovasculaire
    df_clean['Hypertension'] * 2 +                  # Hypertension
    df_clean['Diabetes'] * 2 +                      # Diabète
    df_clean['Depression'] * 2 +                    # Dépression
    (df_clean['SystolicBP'] > 140).astype(int) * 2 +  # HTA systolique
    (df_clean['DiastolicBP'] > 90).astype(int) * 2 +  # HTA diastolique
    (df_clean['Age'] > 75).astype(int) * 2 +        # Age avancé
    (df_clean['PhysicalActivity'] < 2).astype(int) * 2 +  # Sédentarité
    df_clean['Confusion'] +                         # Confusion
    df_clean['Disorientation'] +                    # Désorientation
    df_clean['BehavioralProblems']                  # Problèmes comportementaux
)

# Classification du risque
df_clean['EventRisk'] = pd.cut(df_clean['EventRiskScore'],
                          bins=[-1, 3, 8, 20],
                          labels=[0, 1, 2])  # 0=Faible, 1=Moyen, 2=Élevé

print("\n" + "=" * 60)
print("CIBLE 2 : RISQUE D'ÉVÉNEMENTS")
print("=" * 60)
print(df_clean['EventRisk'].value_counts().sort_index())
print("\n0=Faible | 1=Moyen | 2=Élevé")

df_clean.head()

from sklearn.preprocessing import StandardScaler

# 1. Define ALL continuous columns (16 total)
cols_to_scale = [
    'Age', 'BMI', 'AlcoholConsumption', 'PhysicalActivity',
    'DietQuality', 'SleepQuality', 'SystolicBP', 'DiastolicBP',
    'CholesterolTotal', 'CholesterolLDL', 'CholesterolHDL',
    'CholesterolTriglycerides', 'MMSE', 'FunctionalAssessment',
    'ADL', 'EventRiskScore'
]

# 4. Apply StandardScaler ONLY
scaler = StandardScaler()
df_clean[cols_to_scale] = scaler.fit_transform(df_clean[cols_to_scale])

print("✅ Done! StandardScaler applied to 16 continuous variables.")

df_clean.head()

"""Separation des features et de la cible"""

target_cols = ['CognitiveDecline', 'FallRisk', 'FallRiskLevel', 'EventRiskScore', 'EventRisk']
# Features (X) = all columns except the target columns
X = df_clean.drop(columns=target_cols)

# Targets (y) = multiple target columns
y = df_clean[target_cols]

print(f'Features : {X.shape}')
print(f'Target : {y.shape}')

X.head()

y.head()

from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import numpy as np

# Select only numeric features (excluding targets)
features_for_pca = X.select_dtypes(include=[np.number])

# Apply PCA
pca = PCA()
X_pca = pca.fit_transform(features_for_pca)

# Explained variance
explained_variance_ratio = pca.explained_variance_ratio_
cumulative_variance = np.cumsum(explained_variance_ratio)

# Find number of components for 95% variance
n_components_95 = np.argmax(cumulative_variance >= 0.95) + 1

# Scree plot
plt.figure(figsize=(10, 5))
plt.subplot(1, 2, 1)
plt.plot(range(1, len(explained_variance_ratio) + 1), explained_variance_ratio, 'bo-')
plt.xlabel('Component')
plt.ylabel('Explained Variance Ratio')
plt.title('Scree Plot')

plt.subplot(1, 2, 2)
plt.plot(range(1, len(cumulative_variance) + 1), cumulative_variance, 'ro-')
plt.axhline(y=0.95, color='k', linestyle='--', label='95% threshold')
plt.axvline(x=n_components_95, color='g', linestyle='--', label=f'{n_components_95} components')
plt.xlabel('Number of Components')
plt.ylabel('Cumulative Explained Variance')
plt.title('Cumulative Explained Variance')
plt.legend()

plt.tight_layout()
plt.savefig('pca_analysis.png', dpi=150)
plt.show()

print(f"Components for 95% variance: {n_components_95}")
print(f"Original features: {features_for_pca.shape[1]}")
print(f"Reduction: {features_for_pca.shape[1] - n_components_95} features")

# Apply PCA with optimal components
pca_final = PCA(n_components=n_components_95)
X_pca_reduced = pca_final.fit_transform(features_for_pca)

print(f"\nReduced shape: {X_pca_reduced.shape}")

# Component loadings (feature importance)
components_df = pd.DataFrame(
    pca_final.components_.T,
    columns=[f'PC{i+1}' for i in range(n_components_95)],
    index=features_for_pca.columns
)

# Top features for first 3 components
print("\nTop 5 features per component:")
for i in range(min(3, n_components_95)):
    pc_name = f'PC{i+1}'
    top_features = components_df[pc_name].abs().sort_values(ascending=False).head()
    print(f"\n{pc_name}:")
    print(top_features)

"""# OBJECTIVE 1: CLUSTERING (Unsupervised Learning)
# 1.1 K-Means Clustering
Purpose: Partition patients into K distinct clusters based on feature similarity. Good for finding spherical, equally-sized clusters.

"""

# ============================================
# K-MEANS CLUSTERING
# ============================================

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score, davies_bouldin_score, calinski_harabasz_score
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import numpy as np

# Use the PCA-reduced data from your previous step

# Determine optimal K using Elbow method and Silhouette
inertias = []
silhouettes = []
K_range = range(2, 11)

for k in K_range:
    kmeans_temp = KMeans(n_clusters=k, random_state=42, n_init="auto")
    labels_temp = kmeans_temp.fit_predict(X_pca_reduced)
    inertias.append(kmeans_temp.inertia_)
    silhouettes.append(silhouette_score(X_pca_reduced, labels_temp))

# Plot Elbow and Silhouette
fig, axes = plt.subplots(1, 2, figsize=(12, 5))
axes[0].plot(K_range, inertias, 'bo-')
axes[0].set_xlabel('Number of Clusters (K)')
axes[0].set_ylabel('Inertia')
axes[0].set_title('Elbow Method')
axes[0].grid(True)

axes[1].plot(K_range, silhouettes, 'ro-')
axes[1].set_xlabel('Number of Clusters (K)')
axes[1].set_ylabel('Silhouette Score')
axes[1].set_title('Silhouette Analysis')
axes[1].grid(True)
plt.tight_layout()
plt.show()

# Final K-Means with optimal K (let's use K=4 based on analysis)
kmeans = KMeans(n_clusters=4, random_state=42, n_init="auto")
labels_kmeans = kmeans.fit_predict(X_pca_reduced)

# Evaluation metrics
sil_kmeans = silhouette_score(X_pca_reduced, labels_kmeans)
db_kmeans = davies_bouldin_score(X_pca_reduced, labels_kmeans)
ch_kmeans = calinski_harabasz_score(X_pca_reduced, labels_kmeans)

print("=" * 50)
print("K-MEANS CLUSTERING RESULTS (K=4)")
print("=" * 50)
print(f"Silhouette Score: {sil_kmeans:.4f} (higher is better, range [-1, 1])")
print(f"Davies-Bouldin Index: {db_kmeans:.4f} (lower is better)")
print(f"Calinski-Harabasz Index: {ch_kmeans:.4f} (higher is better)")
print(f"Cluster distribution: {np.bincount(labels_kmeans)}")

# Visualization in 2D
pca_2d = PCA(n_components=2)
X_2d = pca_2d.fit_transform(X_pca_reduced)

plt.figure(figsize=(8, 6))
scatter = plt.scatter(X_2d[:, 0], X_2d[:, 1], c=labels_kmeans, cmap='viridis', s=30, alpha=0.7)
plt.colorbar(scatter, label='Cluster')
plt.title('K-Means Clustering Visualization (PCA 2D)')
plt.xlabel('PC1')
plt.ylabel('PC2')
plt.grid(True, alpha=0.3)
plt.show()

"""# 1.2 DBSCAN (Density-Based Spatial Clustering)
Purpose: Find arbitrarily-shaped clusters and identify outliers (noise points). Good for detecting patients that don't fit any pattern.
"""

!pip install kneed

from sklearn.neighbors import NearestNeighbors
from kneed import KneeLocator
import numpy as np
import matplotlib.pyplot as plt

k = 5  # better for 2D PCA

neighbors = NearestNeighbors(n_neighbors=k)
neighbors_fit = neighbors.fit(X_pca_reduced)
distances, _ = neighbors_fit.kneighbors(X_pca_reduced)

k_distances = np.sort(distances[:, k-1])

# Knee detection (MUCH better)
x = np.arange(len(k_distances))
knee = KneeLocator(x, k_distances, curve='convex', direction='increasing')

eps_optimal = k_distances[knee.knee]

print(f"Optimal eps (knee): {eps_optimal:.3f}")

# Plot
plt.figure(figsize=(10,6))
plt.plot(x, k_distances)
plt.axvline(knee.knee, color='r', linestyle='--', label=f"Elbow at {eps_optimal:.2f}")
plt.legend()
plt.title("K-distance with Knee Detection")
plt.grid()
plt.show()

from sklearn.cluster import DBSCAN
from sklearn.metrics import silhouette_score, davies_bouldin_score

best_score = -1
best_labels = None
best_eps = None

eps_range = np.linspace(eps_optimal * 0.8, eps_optimal * 2, 10)

for eps in eps_range:
    dbscan = DBSCAN(eps=eps, min_samples=k)
    labels = dbscan.fit_predict(X_pca_reduced)

    n_clusters = len(set(labels)) - (1 if -1 in labels else 0)
    n_noise = list(labels).count(-1)

    if n_clusters >= 2:
        mask = labels != -1
        sil = silhouette_score(X_pca_reduced[mask], labels[mask])

        print(f"eps={eps:.2f} | clusters={n_clusters} | noise={100*n_noise/len(labels):.1f}% | sil={sil:.4f}")

        if sil > best_score:
            best_score = sil
            best_labels = labels
            best_eps = eps

labels = best_labels

n_clusters = len(set(labels)) - (1 if -1 in labels else 0)
n_noise = list(labels).count(-1)

print("\nBEST RESULT")
print(f"eps={best_eps:.2f}")
print(f"Clusters: {n_clusters}")
print(f"Noise: {n_noise} ({100*n_noise/len(labels):.2f}%)")

mask = labels != -1
sil = silhouette_score(X_pca_reduced[mask], labels[mask])
db = davies_bouldin_score(X_pca_reduced[mask], labels[mask])

print(f"Silhouette: {sil:.4f}")
print(f"Davies-Bouldin: {db:.4f}")

"""# 1.3 CAH / Hierarchical Clustering (Agglomerative)
Purpose: Build a hierarchy of clusters (dendrogram). Good for understanding nested patient subgroups and relationships between clusters.

"""

# ============================================
# CAH (Classification Ascendante Hiérarchique) / Agglomerative Clustering
# ============================================

from sklearn.cluster import AgglomerativeClustering
from scipy.cluster.hierarchy import dendrogram, linkage
from scipy.spatial.distance import pdist

# Create dendrogram on a sample (for visualization speed)
sample_size = min(500, len(X_pca_reduced))
idx = np.random.choice(len(X_pca_reduced), sample_size, replace=False)
X_sample = X_pca_reduced[idx]

# Compute linkage
linked = linkage(X_sample, method='ward')

plt.figure(figsize=(12, 6))
dendrogram(linked, orientation='top', distance_sort='descending', show_leaf_counts=True, truncate_mode='lastp', p=20)
plt.title('Hierarchical Clustering Dendrogram (Ward Linkage)')
plt.xlabel('Sample Index or (Cluster Size)')
plt.ylabel('Distance')
plt.show()

# Agglomerative Clustering with Ward linkage
cah = AgglomerativeClustering(n_clusters=4, linkage='ward')
labels_cah = cah.fit_predict(X_pca_reduced)

# Evaluation
sil_cah = silhouette_score(X_pca_reduced, labels_cah)
db_cah = davies_bouldin_score(X_pca_reduced, labels_cah)
ch_cah = calinski_harabasz_score(X_pca_reduced, labels_cah)

print("=" * 50)
print("CAH / AGGLOMERATIVE CLUSTERING RESULTS (Ward, K=4)")
print("=" * 50)
print(f"Silhouette Score: {sil_cah:.4f}")
print(f"Davies-Bouldin Index: {db_cah:.4f}")
print(f"Calinski-Harabasz Index: {ch_cah:.4f}")
print(f"Cluster distribution: {np.bincount(labels_cah)}")

# Visualization
plt.figure(figsize=(8, 6))
scatter = plt.scatter(X_2d[:, 0], X_2d[:, 1], c=labels_cah, cmap='viridis', s=30, alpha=0.7)
plt.colorbar(scatter, label='Cluster')
plt.title('CAH (Agglomerative) Clustering Visualization')
plt.xlabel('PC1')
plt.ylabel('PC2')
plt.grid(True, alpha=0.3)
plt.show()

"""# 1.4 GMM (Gaussian Mixture Model)


Purpose: Soft clustering using probabilistic model. Assigns patients to clusters with probability scores. Good when clusters overlap or have different shapes/sizes.
"""

# ============================================
# GMM (GAUSSIAN MIXTURE MODEL)
# ============================================

from sklearn.mixture import GaussianMixture
from sklearn.metrics import silhouette_score, davies_bouldin_score

# Determine optimal number of components using BIC/AIC
n_components_range = range(2, 11)
bics = []
aics = []

for n in n_components_range:
    gmm_temp = GaussianMixture(n_components=n, random_state=42)
    gmm_temp.fit(X_pca_reduced)
    bics.append(gmm_temp.bic(X_pca_reduced))
    aics.append(gmm_temp.aic(X_pca_reduced))

plt.figure(figsize=(10, 5))
plt.plot(n_components_range, bics, 'bo-', label='BIC')
plt.plot(n_components_range, aics, 'ro-', label='AIC')
plt.xlabel('Number of Components')
plt.ylabel('Score')
plt.title('GMM Model Selection (Lower is Better)')
plt.legend()
plt.grid(True)
plt.show()

# Final GMM with optimal components (K=4)
gmm = GaussianMixture(n_components=4, random_state=42)
labels_gmm = gmm.fit_predict(X_pca_reduced)
probs_gmm = gmm.predict_proba(X_pca_reduced)  # Probabilistic assignments

# Evaluation
sil_gmm = silhouette_score(X_pca_reduced, labels_gmm)
db_gmm = davies_bouldin_score(X_pca_reduced, labels_gmm)
ch_gmm = calinski_harabasz_score(X_pca_reduced, labels_gmm)

print("=" * 50)
print("GMM CLUSTERING RESULTS (K=4)")
print("=" * 50)
print(f"Silhouette Score: {sil_gmm:.4f}")
print(f"Davies-Bouldin Index: {db_gmm:.4f}")
print(f"Calinski-Harabasz Index: {ch_gmm:.4f}")
print(f"Log-Likelihood: {gmm.lower_bound_:.4f}")
print(f"Cluster distribution: {np.bincount(labels_gmm)}")

# Show uncertainty (patients with low max probability)
max_probs = np.max(probs_gmm, axis=1)
uncertain_patients = np.sum(max_probs < 0.7)
print(f"Patients with uncertain assignment (prob < 0.7): {uncertain_patients}")

# Visualization with uncertainty as point size
plt.figure(figsize=(8, 6))
scatter = plt.scatter(X_2d[:, 0], X_2d[:, 1], c=labels_gmm, s=50*(max_probs), cmap='viridis', alpha=0.7)
plt.colorbar(scatter, label='Cluster')
plt.title('GMM Clustering (Size = Certainty)')
plt.xlabel('PC1')
plt.ylabel('PC2')
plt.grid(True, alpha=0.3)
plt.show()

"""\# 1.5 Clustering Comparison Summary"""

import numpy as np
import pandas as pd
from sklearn.metrics import silhouette_score, davies_bouldin_score, calinski_harabasz_score

def evaluate(X, labels, name):
    n_clusters = len(set(labels)) - (1 if -1 in labels else 0)
    noise = np.sum(labels == -1)
    noise_pct = noise / len(labels) * 100

    if n_clusters >= 2:
        mask = labels != -1
        sil = silhouette_score(X[mask], labels[mask])
        db = davies_bouldin_score(X[mask], labels[mask])
        ch = calinski_harabasz_score(X[mask], labels[mask])
    else:
        sil, db, ch = None, None, None

    return [name, n_clusters, round(noise_pct, 2), sil, db, ch]

results = [
    evaluate(X_pca_reduced, labels_dbscan, "DBSCAN"),
    evaluate(X_pca_reduced, labels_kmeans, "K-Means"),
    evaluate(X_pca_reduced, labels_cah, "CAH"),
    evaluate(X_pca_reduced, labels_gmm, "GMM"),
]

df = pd.DataFrame(results, columns=[
    "Algorithm", "Clusters", "Noise (%)", "Silhouette", "Davies-Bouldin", "Calinski-Harabasz"
])

print(df)

"""# OBJECTIVE 2: CLASSIFICATION (Supervised Learning)
The goal here is to predict EventRisk (your target: 0=Faible, 1=Moyen, 2=Élevé) using the 32 features. We train models to learn patterns from labeled data.

# 2.1 Data Preparation for Classification
"""

# ============================================
# PREPARATION FOR CLASSIFICATION
# ============================================

from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold
from sklearn.metrics import (accuracy_score, precision_score, recall_score,
                            f1_score, confusion_matrix, classification_report,
                            roc_auc_score, balanced_accuracy_score)
import warnings
warnings.filterwarnings('ignore')

# Define target: EventRisk (0, 1, 2)
y_classification = df_clean['EventRisk'].values

# Features: Use X (32 features) or X_pca_reduced (25 components)
# Recommendation: Try both, but start with original features for interpretability
X_classification = X.values  # Your original X with 32 features (already scaled)

# Stratified split to maintain class distribution
X_train, X_test, y_train, y_test = train_test_split(
    X_classification, y_classification,
    test_size=0.2,
    random_state=42,
    stratify=y_classification
)

print("=" * 50)
print("CLASSIFICATION DATA PREPARATION")
print("=" * 50)
print(f"Training set: {X_train.shape}")
print(f"Test set: {X_test.shape}")
print(f"\nClass distribution in training set:")
print(pd.Series(y_train).value_counts().sort_index())
print(f"\nClass distribution in test set:")
print(pd.Series(y_test).value_counts().sort_index())

"""# 2.2 K-Nearest Neighbors (KNN)
Purpose: Simple, instance-based learning. Predicts based on majority class of K nearest neighbors in feature space. Good baseline model.

"""

# ============================================
# K-NEAREST NEIGHBORS (KNN)
# ============================================

from sklearn.neighbors import KNeighborsClassifier
import seaborn as sns  # ADD THIS IMPORT
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import (accuracy_score, balanced_accuracy_score,
                            f1_score, confusion_matrix, classification_report)

# Find optimal K
k_range = range(1, 21)
cv_scores = []

for k in k_range:
    knn_temp = KNeighborsClassifier(n_neighbors=k)
    scores = cross_val_score(knn_temp, X_train, y_train, cv=5, scoring='f1_macro')
    cv_scores.append(scores.mean())

optimal_k = k_range[np.argmax(cv_scores)]

plt.figure(figsize=(8, 5))
plt.plot(k_range, cv_scores, 'bo-')
plt.axvline(x=optimal_k, color='r', linestyle='--', label=f'Optimal K={optimal_k}')
plt.xlabel('Number of Neighbors (K)')
plt.ylabel('Cross-Validated F1-Macro')
plt.title('KNN Hyperparameter Tuning')
plt.legend()
plt.grid(True)
plt.show()

# Final KNN model
knn = KNeighborsClassifier(n_neighbors=optimal_k)
knn.fit(X_train, y_train)
y_pred_knn = knn.predict(X_test)

# Evaluation
print("=" * 50)
print(f"KNN RESULTS (K={optimal_k})")
print("=" * 50)
print(f"Accuracy: {accuracy_score(y_test, y_pred_knn):.4f}")
print(f"Balanced Accuracy: {balanced_accuracy_score(y_test, y_pred_knn):.4f}")
print(f"F1-Macro: {f1_score(y_test, y_pred_knn, average='macro'):.4f}")
print(f"F1-Weighted: {f1_score(y_test, y_pred_knn, average='weighted'):.4f}")

print("\nDetailed Classification Report:")
print(classification_report(y_test, y_pred_knn, target_names=['Faible (0)', 'Moyen (1)', 'Élevé (2)']))

# Confusion Matrix
cm_knn = confusion_matrix(y_test, y_pred_knn)
plt.figure(figsize=(6, 5))
sns.heatmap(cm_knn, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Faible', 'Moyen', 'Élevé'],
            yticklabels=['Faible', 'Moyen', 'Élevé'])
plt.title('KNN Confusion Matrix')
plt.ylabel('True Label')
plt.xlabel('Predicted Label')
plt.show()

"""# 2.3 Support Vector Machine (SVM)
Purpose: Finds optimal hyperplane to separate classes. Effective in high-dimensional spaces. Good for complex decision boundaries.
"""

# ============================================
# SUPPORT VECTOR MACHINE (SVM)
# ============================================

from sklearn.svm import SVC
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import cross_val_score
from sklearn.metrics import (accuracy_score, balanced_accuracy_score,
                            f1_score, confusion_matrix, classification_report)

# Test different kernels
kernels = ['linear', 'rbf', 'poly']
kernel_results = []

for kernel in kernels:
    svm_temp = SVC(kernel=kernel, random_state=42)
    scores = cross_val_score(svm_temp, X_train, y_train, cv=5, scoring='f1_macro')
    kernel_results.append((kernel, scores.mean()))

best_kernel = max(kernel_results, key=lambda x: x[1])[0]
print(f"Best kernel from CV: {best_kernel}")

# Final SVM with best kernel
svm = SVC(kernel=best_kernel, random_state=42, probability=True)
svm.fit(X_train, y_train)
y_pred_svm = svm.predict(X_test)

# Evaluation
print("=" * 50)
print(f"SVM RESULTS (Kernel={best_kernel})")
print("=" * 50)
print(f"Accuracy: {accuracy_score(y_test, y_pred_svm):.4f}")
print(f"Balanced Accuracy: {balanced_accuracy_score(y_test, y_pred_svm):.4f}")
print(f"F1-Macro: {f1_score(y_test, y_pred_svm, average='macro'):.4f}")
print(f"F1-Weighted: {f1_score(y_test, y_pred_svm, average='weighted'):.4f}")

print("\nDetailed Classification Report:")
print(classification_report(y_test, y_pred_svm, target_names=['Faible (0)', 'Moyen (1)', 'Élevé (2)']))

# Confusion Matrix
cm_svm = confusion_matrix(y_test, y_pred_svm)
plt.figure(figsize=(6, 5))
sns.heatmap(cm_svm, annot=True, fmt='d', cmap='Greens',
            xticklabels=['Faible', 'Moyen', 'Élevé'],
            yticklabels=['Faible', 'Moyen', 'Élevé'])
plt.title('SVM Confusion Matrix')
plt.ylabel('True Label')
plt.xlabel('Predicted Label')
plt.show()

"""# 2.4 Random Forest
Purpose: Ensemble of decision trees. Robust, handles non-linear relationships, provides feature importance. Good baseline for structured data.
"""

# ============================================
# RANDOM FOREST
# ============================================

from sklearn.ensemble import RandomForestClassifier

# Hyperparameter tuning (simplified grid search)
n_estimators_range = [50, 100, 200]
max_depth_range = [5, 10, None]

best_rf_score = 0
best_rf_params = {}

for n_est in n_estimators_range:
    for depth in max_depth_range:
        rf_temp = RandomForestClassifier(n_estimators=n_est, max_depth=depth, random_state=42)
        scores = cross_val_score(rf_temp, X_train, y_train, cv=5, scoring='f1_macro')
        mean_score = scores.mean()
        if mean_score > best_rf_score:
            best_rf_score = mean_score
            best_rf_params = {'n_estimators': n_est, 'max_depth': depth}

print(f"Best RF params: {best_rf_params}")

# Final Random Forest
rf = RandomForestClassifier(**best_rf_params, random_state=42)
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)

# Evaluation
print("=" * 50)
print("RANDOM FOREST RESULTS")
print("=" * 50)
print(f"Accuracy: {accuracy_score(y_test, y_pred_rf):.4f}")
print(f"Balanced Accuracy: {balanced_accuracy_score(y_test, y_pred_rf):.4f}")
print(f"F1-Macro: {f1_score(y_test, y_pred_rf, average='macro'):.4f}")
print(f"F1-Weighted: {f1_score(y_test, y_pred_rf, average='weighted'):.4f}")

print("\nDetailed Classification Report:")
print(classification_report(y_test, y_pred_rf, target_names=['Faible (0)', 'Moyen (1)', 'Élevé (2)']))

# Feature Importance
feature_importance = pd.DataFrame({
    'feature': X.columns,
    'importance': rf.feature_importances_
}).sort_values('importance', ascending=False)

plt.figure(figsize=(10, 6))
sns.barplot(data=feature_importance.head(15), x='importance', y='feature', palette='viridis')
plt.title('Top 15 Feature Importances (Random Forest)')
plt.tight_layout()
plt.show()

# Confusion Matrix
cm_rf = confusion_matrix(y_test, y_pred_rf)
plt.figure(figsize=(6, 5))
sns.heatmap(cm_rf, annot=True, fmt='d', cmap='Oranges',
            xticklabels=['Faible', 'Moyen', 'Élevé'],
            yticklabels=['Faible', 'Moyen', 'Élevé'])
plt.title('Random Forest Confusion Matrix')
plt.ylabel('True Label')
plt.xlabel('Predicted Label')
plt.show()

"""# 2.5 Gradient Boosting (XGBoost-style)
Purpose: Sequential ensemble that corrects previous errors. Often best performance for tabular data. Good for capturing complex patterns.
"""

# ============================================
# STEP 1: DATA PREPARATION FOR CLASSIFICATION
# ============================================

from sklearn.model_selection import train_test_split
from sklearn.metrics import (accuracy_score, balanced_accuracy_score, f1_score,
                            confusion_matrix, classification_report)
import numpy as np
import pandas as pd

# Define target: EventRisk (0=Faible, 1=Moyen, 2=Élevé)
y_classification = df_clean['EventRisk'].values

# Features: Use X (32 features) - already scaled from your previous step
X_classification = X.values

# Stratified split to maintain class distribution
X_train, X_test, y_train, y_test = train_test_split(
    X_classification, y_classification,
    test_size=0.2,
    random_state=42,
    stratify=y_classification
)

print("=" * 50)
print("DATA PREPARATION COMPLETE")
print("=" * 50)
print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")
print(f"\nClass distribution in train: {np.bincount(y_train)}")
print(f"Class distribution in test: {np.bincount(y_test)}")

# ============================================
# GRADIENT BOOSTING
# ============================================

from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import cross_val_score  # ADD THIS
from sklearn.metrics import (accuracy_score, balanced_accuracy_score,  # ADD THESE
                            f1_score, confusion_matrix, classification_report)
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns  # ADD THIS

# Hyperparameter tuning
learning_rates = [0.05, 0.1, 0.2]
n_estimators_range = [50, 100, 200]

best_gb_score = 0
best_gb_params = {}

for lr in learning_rates:
    for n_est in n_estimators_range:
        gb_temp = GradientBoostingClassifier(learning_rate=lr, n_estimators=n_est, random_state=42)
        scores = cross_val_score(gb_temp, X_train, y_train, cv=5, scoring='f1_macro')
        mean_score = scores.mean()
        if mean_score > best_gb_score:
            best_gb_score = mean_score
            best_gb_params = {'learning_rate': lr, 'n_estimators': n_est}

print(f"Best GB params: {best_gb_params}")

# Final Gradient Boosting
gb = GradientBoostingClassifier(**best_gb_params, random_state=42)
gb.fit(X_train, y_train)
y_pred_gb = gb.predict(X_test)

# Evaluation
print("=" * 50)
print("GRADIENT BOOSTING RESULTS")
print("=" * 50)
print(f"Accuracy: {accuracy_score(y_test, y_pred_gb):.4f}")
print(f"Balanced Accuracy: {balanced_accuracy_score(y_test, y_pred_gb):.4f}")
print(f"F1-Macro: {f1_score(y_test, y_pred_gb, average='macro'):.4f}")
print(f"F1-Weighted: {f1_score(y_test, y_pred_gb, average='weighted'):.4f}")

print("\nDetailed Classification Report:")
print(classification_report(y_test, y_pred_gb, target_names=['Faible (0)', 'Moyen (1)', 'Élevé (2)']))

# Feature Importance
gb_importance = pd.DataFrame({
    'feature': X.columns,
    'importance': gb.feature_importances_
}).sort_values('importance', ascending=False)

plt.figure(figsize=(10, 6))
sns.barplot(data=gb_importance.head(15), x='importance', y='feature', palette='plasma')
plt.title('Top 15 Feature Importances (Gradient Boosting)')
plt.tight_layout()
plt.show()

# Confusion Matrix
cm_gb = confusion_matrix(y_test, y_pred_gb)
plt.figure(figsize=(6, 5))
sns.heatmap(cm_gb, annot=True, fmt='d', cmap='Reds',
            xticklabels=['Faible', 'Moyen', 'Élevé'],
            yticklabels=['Faible', 'Moyen', 'Élevé'])
plt.title('Gradient Boosting Confusion Matrix')
plt.ylabel('True Label')
plt.xlabel('Predicted Label')
plt.show()

"""# 2.6 Classification Comparison & Final Selection

"""

# ============================================
# CLASSIFICATION COMPARISON & CROSS-VALIDATION
# ============================================

# Compile results
classification_results = [
    {
        'Model': f'KNN (K={optimal_k})',
        'Accuracy': accuracy_score(y_test, y_pred_knn),
        'Balanced_Accuracy': balanced_accuracy_score(y_test, y_pred_knn),
        'F1_Macro': f1_score(y_test, y_pred_knn, average='macro'),
        'F1_Weighted': f1_score(y_test, y_pred_knn, average='weighted')
    },
    {
        'Model': f'SVM ({best_kernel})',
        'Accuracy': accuracy_score(y_test, y_pred_svm),
        'Balanced_Accuracy': balanced_accuracy_score(y_test, y_pred_svm),
        'F1_Macro': f1_score(y_test, y_pred_svm, average='macro'),
        'F1_Weighted': f1_score(y_test, y_pred_svm, average='weighted')
    },
    {
        'Model': 'Random Forest',
        'Accuracy': accuracy_score(y_test, y_pred_rf),
        'Balanced_Accuracy': balanced_accuracy_score(y_test, y_pred_rf),
        'F1_Macro': f1_score(y_test, y_pred_rf, average='macro'),
        'F1_Weighted': f1_score(y_test, y_pred_rf, average='weighted')
    },
    {
        'Model': 'Gradient Boosting',
        'Accuracy': accuracy_score(y_test, y_pred_gb),
        'Balanced_Accuracy': balanced_accuracy_score(y_test, y_pred_gb),
        'F1_Macro': f1_score(y_test, y_pred_gb, average='macro'),
        'F1_Weighted': f1_score(y_test, y_pred_gb, average='weighted')
    }
]

results_df = pd.DataFrame(classification_results)
print("\n" + "=" * 80)
print("CLASSIFICATION MODELS COMPARISON (Test Set)")
print("=" * 80)
print(results_df.round(4).to_string(index=False))

# 5-Fold Cross-Validation on full dataset for best model
print("\n" + "=" * 80)
print("5-FOLD CROSS-VALIDATION ON FULL DATASET")
print("=" * 80)

models_for_cv = {
    'KNN': KNeighborsClassifier(n_neighbors=optimal_k),
    'SVM': SVC(kernel=best_kernel, random_state=42),
    'Random Forest': RandomForestClassifier(**best_rf_params, random_state=42),
    'Gradient Boosting': GradientBoostingClassifier(**best_gb_params, random_state=42)
}

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

for name, model in models_for_cv.items():
    f1_cv = cross_val_score(model, X_classification, y_classification, cv=cv, scoring='f1_macro')
    acc_cv = cross_val_score(model, X_classification, y_classification, cv=cv, scoring='accuracy')
    print(f"\n{name}:")
    print(f"  F1-Macro: {f1_cv.mean():.4f} (+/- {f1_cv.std()*2:.4f})")
    print(f"  Accuracy: {acc_cv.mean():.4f} (+/- {acc_cv.std()*2:.4f})")

# Select best model (highest F1-Macro CV score)
best_model_name = results_df.loc[results_df['F1_Macro'].idxmax(), 'Model']
print(f"\n{'='*80}")
print(f"BEST MODEL SELECTED: {best_model_name}")
print(f"{'='*80}")

# Final detailed report for best model
if 'KNN' in best_model_name:
    best_model_final = knn
    y_pred_best = y_pred_knn
elif 'SVM' in best_model_name:
    best_model_final = svm
    y_pred_best = y_pred_svm
elif 'Random Forest' in best_model_name:
    best_model_final = rf
    y_pred_best = y_pred_rf
else:
    best_model_final = gb
    y_pred_best = y_pred_gb

print("\nFinal Detailed Report:")
print(classification_report(y_test, y_pred_best, target_names=['Faible (0)', 'Moyen (1)', 'Élevé (2)']))