import { CameraZone } from './camera-device.model';

/**
 * Pairing Token Model
 *
 * Defines types and interfaces for ESP32-CAM pairing token provisioning.
 * Tokens are generated by admins/caregivers and consumed by cameras during setup.
 */

/**
 * Pairing token response - represents a generated provisioning token
 */
export interface PairingToken {
  id: string;
  token: string;
  patientId: string;
  zone: CameraZone;
  createdBy: string;
  createdAt: string;  // ISO timestamp
  expiresAt: string;  // ISO timestamp
  used: boolean;
}

/**
 * Request to generate a new pairing token
 */
export interface GeneratePairingTokenRequest {
  patientId: string;
  zone: CameraZone;
}

/**
 * Camera provision response - returned when a camera self-registers
 */
export interface CameraProvisionResponse {
  deviceId: string;
  patientId: string;
  zone: CameraZone;
  serverUrl: string;
}
